language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - gcovr

script:
  - mkdir build
  - cd build
  - if [[ "$CC" == "gcc" ]]; then cmake -DCodeCoverage=ON .. ; else cmake  ..; fi
  - make
  - make test
  - if [[ "$CC" == "gcc" ]]; then make coverage; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
