language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - gcovr

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
  - chmod +x /tmp/cc-test-reporter
  - /tmp/cc-test-reporter before-build

script:
  - mkdir build
  - cd build
  - if [[ "$CC" == "gcc" ]]; then cmake -DCodeCoverage=ON .. ; else cmake  ..; fi
  - make
  - make test
  - if [[ "$CC" == "gcc" ]]; then make coverage; fi

after_script:
  - /tmp/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
